when:
  - event: [push, manual]

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      partial: false
      recursive: true

steps:
  - name: mirror to Github
    when:
      - event: [ push, manual ]
        branch: [ master, main ]
    depends_on: []
    image: codeberg.org/mathisdt/buildhelper:latest
    pull: true
    environment:
      TOKEN_GITHUB:
        from_secret: TOKEN_GITHUB
    commands: |
      git remote add github https://mathisdt:$TOKEN_GITHUB@github.com/mathisdt/$CI_REPO_NAME.git
      git push github
  - name: build
    when:
      - event: [ push, manual ]
    depends_on: []
    image: python:3.14-slim-trixie
    pull: true
    commands: |
      export TZ=Europe/Berlin
      pip3 install twine tomli tomli-w
  - name: pypi-release
    when:
      - event: manual
        branch: [ master, main ]
    depends_on: [ build ]
    image: python:3.14-slim-trixie
    pull: true
    environment:
      PYPI_TOKEN:
        from_secret: PYPI_TOKEN
    commands: |
      export TZ=Europe/Berlin
      if [ -z "$PYPI_TOKEN" ]; then
        echo "no PyPI token given, not uploading to PyPI"
        exit 1
      fi
      if [ -n "$CI_COMMIT_SOURCE_BRANCH" ]; then
        echo "not uploading to PyPI, we're in a PR"
        exit 2
      fi
      if [ "$CI_COMMIT_BRANCH" != "master" -a "$CI_COMMIT_BRANCH" != "main" ]; then
        echo "not uploading to PyPI, we're on branch $CI_COMMIT_BRANCH"
        exit 3
      fi
      echo "uploading to PyPI"
      TWINE_PASSWORD="$PYPI_TOKEN" python3 -m twine upload --repository pypi --verbose dist/*
  - name: increase-version
    when:
      - event: manual
        branch: [ master, main ]
    depends_on: [ pypi-release ]
    image: python:3.14-slim-trixie
    pull: true
    environment:
      TOKEN_REPO_READWRITE:
        from_secret: TOKEN_REPO_READWRITE
    commands: |
      echo "increase version number"
      python3 increase-version.py
      echo "commit and push increased version"
      git config --global user.name "Woodpacker Pipeline"
      git config --global user.email "nonexistant@example.com"
      git add pyproject.toml
      git commit -m "increase version number"
      git remote add codeberg_http https://$CI_REPO_OWNER:$TOKEN_REPO_READWRITE@codeberg.org/$CI_REPO_OWNER/$CI_REPO_NAME.git
      git push codeberg_http
