name: build
run-name: build commit with earthly

on:
  push

jobs:
  release:
    uses: mathisdt/workflows/.github/workflows/earthly.yaml@master
    with:
      earthly-target: +build-and-release-on-pypi
    secrets: inherit
